/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation("com.squareup.moshi:moshi:1.13.0")
    implementation("javax.servlet:javax.servlet-api:4.0.1")
}

group = "ru.clevertec"
version = "1.0-SNAPSHOT"
description = "CheckRunner"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

task<ru.clevertec.FileLoader>("load") {
    fileUrl = "https://github.com/SiarheiNikonov/Test/blob/main/task2.png?raw=true"
    outDirectory = "outDir"
}
