spring:

  liquibase:
    enabled: true
    url: jdbc:postgresql://127.0.0.1:5432/products
    password: 7132927
    driver-class-name: org.postgresql.Driver
    user: postgres

  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/products
    password: 7132927
    username: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

